#:kivy 2.1.0
<HomeScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: '¡Bienvenido a la aplicación NFC!'
        Button:
            text: 'Escanear Producto'
            on_press: print('Escanear Producto presionado')
        Button:
            text: 'Ver Carrito de Compras'
            on_press: print('Ver Carrito de Compras presionado')
        Button:
            text: 'Ir a Pago'
            on_press: print('Ir a Pago presionado')
